### PR TITLE
Changed layout of the enter form and confirm

### PR DESCRIPTION
**Pull request by JKirkYuan**
Feel free to drop a few comments. I changed up the two pages, test it out and let me know some problems and I'll try to fix them!

### CODE REVIEW

**Comment by karimsa** [comment]
Swap out all the uses of `px` for `rem`s - Bootstrap 4 sets proper breakpoints for font-size on `<body>`.

**Comment by karimsa** [comment]
And improved spacing. Maybe push it through a CSS beautifier to fix whitespacing.

**Comment by jaydenwindle** [comment]
@karimsa px is fine for now, we can change it to rem after the demo tomorrow.

**Comment by karimsa** [comment]
Yes, but the issue should be addressed at some point.

**Comment by vikrambombhi** [comment]
@karimsa can u make it a issue so we get back to it at some point

**Comment by vikrambombhi** [comment]
This looks good to me(although admittedly i have no sense of design). Id say merge it to master for tomorrow and throw any further issues on the backlog(unless its build breaking)

**Pull request merged**
