### PR TITLE
Changed css to rem from px (fix #33)

### LINKED ISSUE #33: Change usage of px to rem in front end design
Bootstrap 4 correctly sets the `font-size` on `<body>` with appropriate responsive breakpoints, therefore our CSS should be using `rem` over `px`.

### PR DESCRIPTION
**Pull request by JKirkYuan**
## Description

Nothing special, converted all uses of px to rem

## Motivation and Context
See issue #33 

## How Has This Been Tested?
N/A

## Screenshots (if appropriate):
N/A

## Types of changes

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ - ] New feature (non-breaking change which adds functionality)
- [ - ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x ] My code follows the code style of this project.
- [ - ] My change requires a change to the documentation.
- [ - ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by karimsa** [comment]
Looks good - can you try to figure out how we could use something like [mappy-breakpoint](https://github.com/zellwk/mappy-breakpoints) to handle breakpoints? Or can we take the breakpoints defined by bootstrap and turn them into a separate SASS file with variables?

**Comment by JKirkYuan** [comment]
screen shot 2017-04-14 at 11 41 33 am

I think we can actually define variables ourselves and use those values as media breakpoints shown here, do you think that would be a good alternative to mappy-breakpoints? It's kind of weird because when I tried to use their syntax, nothing was working :/

**Comment by karimsa** [comment]
Yeah, I think that's best. Let's use the breakpoints from Bootstrap, but put them into our own variables.

screen shot 2017-04-14 at 11 52 18 am

Something to the effect of [this](https://davidwalsh.name/write-media-queries-sass).

**Comment by karimsa** [comment]
Also, for future PRs, follow the contribution guide for naming branches.

**Pull request merged**
