### PR TITLE
Add initial contribution guide (fix #40)

### LINKED ISSUE #40: Needs a contribution guide
We need a clearly defined contribution guide to outline how contributions should work (should be generic enough to be used internally as well as externally).

### PR DESCRIPTION
**Pull request by karimsa**
## Description

Adds an initial contribution guide.

## Motivation and Context

See issue #40.

## How Has This Been Tested?

N/a.

## Screenshots (if appropriate):

N/a.

## Types of changes

- [ - ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ - ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by jaydenwindle — COMMENTED** [review]
Is it worth mentioning something about squashing commits?

**Comment by karimsa** [comment]
I thought of that, but PRs can be "squashed & merged" at the same time now via Github so we should always do that. I can mention that it will be done by us?

**Comment by jaydenwindle** [comment]
Oh cool! Didn't realize that github had that. Yeah, maybe just mention that if you're merging a PR do squash and merge

**Comment by karimsa** [comment]
Updated - thoughts?

**Comment by jaydenwindle** [comment]
Looks good to me!

**Pull request merged**
